### ISSUE TITLE
4 digit format

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Nordic-Museum-Audio-Guide#14]
Make the app work with either 3 digit or 4 digit codes. I think I know how to do this once I get the build process to work :)

This is needed for the second museum that wants to use the app.

**Comment by RubenSandwich** [comment]
@Ambrosiani I was looking into this last night and I believe the search by numbers functionality needs to be rewritten to support this, it has too many assumptions built into it right now. 

Another thing related to this feature is that it was written to move to the next screen as soon as the number was entered. So if we accept 3 and 4 digits then the 3 digit code "344" would always hit before the 4 digit code "3443". I really like the transition as soon as you enter the code instead of having to press another button. Do you mind if I add an appSettings.json file that determines the number of digits in the search by numbers code? This appSettings.json file would also contain the google analytics id that we currently have here: https://github.com/NordicMuseum/Nordic-Museum-Audio-Guide/blob/master/app/data/trackingID.js.

**Comment by Ambrosiani** [comment]
yes, all stops need to have the same number of digits. Take a look at #22 and see if that's a valid approach.
