### ISSUE TITLE
Add android build

### ISSUE THREAD

**Issue by Ambrosiani** [NordicMuseum/Nordic-Museum-Audio-Guide#17]
If possible, when upgrading to the latest React Native we should add building to android (without the Near Me tab), or at least prepare a list of which dependencies and local modules need to be adapted for android compatibility.

**Comment by RubenSandwich** [comment]
A basic outline of the required android work:
- Safer/more future proof RTL/LTR switch
(No idea yet)
- Move Audio Library to a community module
(https://github.com/zmxv/react-native-sound)
- Move Bluetooth to a community module
(No Idea yet)
- Use React Native voiceover module (They have since added all the features we needed internally.)
(https://facebook.github.io/react-native/docs/accessibilityinfo)
