### ISSUE TITLE
Audio (Native Module - Library Track)

### ISSUE THREAD

**Issue by sticknor** [NordicMuseum/Nordic-Museum-Audio-Guide#30]

**Comment by Ambrosiani** [comment]
@sticknor @RubenSandwich there's a change in the mp3 file names I'd like to implement at the same time. right now the files are named `id/language.mp3` which means that there are 200 different sv.mp3 and en.mp3. Can we change this to `id/id-language.mp3` instead, i.e. repeating the id in the filename? so instead of 201/sv.mp3 it would be 201/201-sv.mp3. I can batch rename the files. will make it easier to find stuff :)

**Comment by RubenSandwich** [comment]
Yeah that shouldn’t cause too many problems. Let’s do it.

**Comment by Ambrosiani** [comment]
@RubenSandwich @sticknor awesome, I'll figure out a good batch renaming here locally & can push new placeholder mp3's after that.

**Comment by Ambrosiani** [comment]
accidentally included the .pbxproj and package-lock files but here are the renamed audio files… https://github.com/NordicMuseum/Nordic-Museum-Audio-Guide/commit/6df35098ea0fedfc85cebf77b8a57a7921f9b825
